// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDH4u5_DtAB9lwN_emU45Ecf90mhzsC4I',
    appId: '1:1001792393824:web:72184bfb3a44aa7c542905',
    messagingSenderId: '1001792393824',
    projectId: 'moneglise-8c5c8',
    authDomain: 'moneglise-8c5c8.firebaseapp.com',
    storageBucket: 'moneglise-8c5c8.firebasestorage.app',
    measurementId: 'G-PTS4BXRFPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7mUS89fOAOZLM6rW-PWt7iVj9Y6PLv_g',
    appId: '1:1001792393824:android:b6b03bdd338fef5a542905',
    messagingSenderId: '1001792393824',
    projectId: 'moneglise-8c5c8',
    storageBucket: 'moneglise-8c5c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEywJw761izTTHGm03dmOef976hFhM59s',
    appId: '1:1001792393824:ios:1223fca8302cf280542905',
    messagingSenderId: '1001792393824',
    projectId: 'moneglise-8c5c8',
    storageBucket: 'moneglise-8c5c8.firebasestorage.app',
    iosBundleId: 'com.example.claude',
  );
}
